# 6. Модуль NumPy. Массивы

**Однако массивы обладают особым свойством: элемент по любому номеру из массива можно получить за одно и то же время. Другими словами, неважно, находится элемент в начале, в середине или в конце списка — на времени получения элемента из массива по индексу (номеру) это никак не скажется.**

**Чем же всё это отличается от списка?**
   + **В списке не гарантируется получение любого элемента по индексу за одинаковое время (обычно чем больше индекс, тем дольше занимает время получения элемента).**
   + **Также с совокупностью элементов списка работать дольше, чем с элементами массива. На самом деле Python list является чем-то средним между классическим списком из теории структур данных и массивом, но по скорости он тоже проигрывает массивам.**

## Массивы в Numpy

### Создание массива из списка

In [2]:
import numpy as np

In [3]:
arr=np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
nd_arr = np.array([
    [12,45,78],
    [34,56,13],
    [12,98,76]
])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

### Типы данных в массиве

In [6]:
arr = np.array([1,5,2,9,10])
arr.dtype

dtype('int64')

In [7]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [8]:
arr[2]=2000
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [9]:
arr[2]=125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [10]:
arr[2]='12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [11]:
arr[2]='test'
arr

ValueError: invalid literal for int() with base 10: 'test'

**Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float128):**