# 7. Модуль NumPy. Действия с массивами


# Действия с массивами

## Изменение формы массива


In [1]:
import numpy  as np

In [3]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr = np.arange(8)
arr_new = arr.reshape((2,4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
arr = np.arange(8)
arr_new = arr.reshape((2,4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [9]:
arr = np.arange(8)
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
arr_transp = arr.transpose()
arr_transp

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

## Индексы и срезы в массивах