# 8. Модуль NumPy. Операции с векторами

## Векторы в NumPy и арифметика

В программировании **вектором** называют одномерный проиндексированный набор данных, другими словами — одномерный массив.

In [1]:
import numpy as np


In [2]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [3]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [4]:
[x +y for x,y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [5]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [7]:
vec = np.arange(5)
vec*10


array([ 0, 10, 20, 30, 40])

In [8]:
vec**3

array([ 0,  1,  8, 27, 64])

In [9]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2

array([False, False,  True, False])

In [11]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

## Продвинутые операции с векторами

---

In [13]:
vec=np.array([3,4])

In [15]:
#  определяем длину вектора
length = np.sqrt(np.sum(vec**2))
print(length)

5.0


In [16]:
length = np.linalg.norm(vec)
print(length)

5.0


In [17]:
# находим разность векторов
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distanse = np.sqrt(np.sum((vec1 - vec2)**2))
print(distanse)


12.206555615733702


In [18]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distanse = np.linalg.norm(vec1-vec2)
print(distanse)

12.206555615733702


Наконец, скалярным произведением двух векторов называют сумму произведений их соответствующих координат. Вот формула для скалярного произведения векторов и из координат:

In [19]:
vec1 = np.arange(1,6)
vec2 = np.linspace(10,20,5)
scal = np.sum(vec1*vec2)
scal

250.0

In [20]:
scal = np.dot(vec1, vec2)
scal

250.0

In [21]:
# если скалярное произведение двух векторов равно нулу, то они **перпенидикулярны** друг другу
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

Базовые статистические функции для векторов

In [23]:
vec = np.array([2,7,18,28,18,1,8,4])
np.min(vec)

1

In [24]:
vec.max()

28

In [25]:
vec.mean()

10.75